version: "3.7"

services:
  gim:
    image: "wangxiaoqiang/server:${VER_TAG:-latest}"
    container_name: server
    restart: always
    volumes:
      - ../src/config.json:/code/src/config.json
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    environment:
      GIN_MODE: "release"
